services:
  # client:
  #   container_name: debug_dev_client
  #   build: ./client
  #   image: debug_client
  #   ports: 
  #     - 8080:8080
  #   working_dir: /code
  #   volumes:
  #     - type: bind
  #       source: ./client
  #       target: /code
  #   command: [ "http-server" ]
  server:
    container_name: debug_dev_server
    ports: 
      - 3000:3000
    environment: 
      - PGUSER=postgres
      - PGHOST=db
      - PGPASSWORD=postpassword
      - PGDATABASE=habittracking
      - PGPORT=5432
      - NODE_ENV=development
    depends_on:
      - db
    command: bash -c "npm install && npm run seedDev && npm run dev"

  db:
    container_name: debug_dev_db
    volumes:
      - "dbdata:/var/lib/postgresql/data"
    environment: 
      - POSTGRES_DB=habittracking
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postpassword
volumes:
  dbdata:
networks: 
  default:
    name: debug_server
