version: '3'
services:
  server:
    image: node:12.18.4
    working_dir: /code
    volumes:
      - type: bind
        source: habit-tracking/habit-server
        target: /code
  db:
    image: postgres:latest
    environment: 
      - POSTGRES_USER=postgres
    volumes:
      - "./db:/docker-entrypoint-initdb.d/:ro"